<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // MONITORS
            [
                'name' => 'Dell UltraSharp 27" 4K',
                'description' => 'Professional 4K monitor with IPS panel, perfect for designers and content creators.',
                'price' => 449.99,
                'stock_quantity' => 15,
                'category' => 'monitors',
                'likes' => 142,
                'image_url' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'LG 34" UltraWide Curved',
                'description' => 'Immersive 34-inch curved ultrawide monitor with 3440x1440 resolution.',
                'price' => 599.99,
                'stock_quantity' => 8,
                'category' => 'monitors',
                'likes' => 256,
                'image_url' => 'https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Samsung Odyssey G7 32"',
                'description' => 'High-performance gaming monitor with 240Hz refresh rate and QLED display.',
                'price' => 699.99,
                'stock_quantity' => 0,
                'category' => 'monitors',
                'likes' => 387,
                'image_url' => 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'ASUS ROG Swift 27" 360Hz',
                'description' => 'Ultimate esports gaming monitor with 360Hz refresh rate.',
                'price' => 799.99,
                'stock_quantity' => 12,
                'category' => 'monitors',
                'likes' => 421,
                'image_url' => 'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'BenQ PD2700U 27" 4K',
                'description' => 'Professional designer monitor with 100% sRGB color accuracy.',
                'price' => 549.99,
                'stock_quantity' => 20,
                'category' => 'monitors',
                'likes' => 198,
                'image_url' => 'https://images.unsplash.com/photo-1551739440-5dd934d3a94a?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'AOC 24" Full HD Gaming',
                'description' => 'Budget-friendly gaming monitor with 144Hz refresh rate.',
                'price' => 179.99,
                'stock_quantity' => 35,
                'category' => 'monitors',
                'likes' => 89,
                'image_url' => 'https://images.unsplash.com/photo-1616763355603-9755a640a287?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'ViewSonic VP2768 27" Pro',
                'description' => 'Professional monitor with factory calibration.',
                'price' => 429.99,
                'stock_quantity' => 10,
                'category' => 'monitors',
                'likes' => 156,
                'image_url' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'MSI Optix MAG274QRF-QD',
                'description' => 'Rapid IPS gaming monitor with Quantum Dot technology.',
                'price' => 399.99,
                'stock_quantity' => 18,
                'category' => 'monitors',
                'likes' => 267,
                'image_url' => 'https://images.unsplash.com/photo-1625453336315-33768a8d0be6?w=600&h=400&fit=crop',
            ],

            // GAMING PCS
            [
                'name' => 'RTX 4070 Gaming Beast',
                'description' => 'Powerful gaming PC with RTX 4070, Intel i7-13700K, 32GB DDR5 RAM.',
                'price' => 1499.99,
                'stock_quantity' => 5,
                'category' => 'pcs',
                'likes' => 534,
                'image_url' => 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Workstation Pro Ultimate',
                'description' => 'Professional workstation with AMD Ryzen 9 7950X, RTX 4080.',
                'price' => 2299.99,
                'stock_quantity' => 3,
                'category' => 'pcs',
                'likes' => 312,
                'image_url' => 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Budget Gaming Starter',
                'description' => 'Entry-level gaming PC with RTX 4060, Ryzen 5 7600.',
                'price' => 899.99,
                'stock_quantity' => 22,
                'category' => 'pcs',
                'likes' => 678,
                'image_url' => 'https://images.unsplash.com/photo-1560242277-e8e1f0b9f42e?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Ultra High-End Enthusiast',
                'description' => 'Top-tier gaming PC with RTX 4090, Intel i9-14900K.',
                'price' => 3499.99,
                'stock_quantity' => 0,
                'category' => 'pcs',
                'likes' => 892,
                'image_url' => 'https://images.unsplash.com/photo-1600861194942-f883de0dfe96?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Compact Mini ITX Build',
                'description' => 'Small form factor gaming PC with RTX 4070 Ti.',
                'price' => 1799.99,
                'stock_quantity' => 7,
                'category' => 'pcs',
                'likes' => 445,
                'image_url' => 'https://images.unsplash.com/photo-1593640495253-23196b27a87f?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Streaming & Content Creator',
                'description' => 'Optimized for streaming with dual PC setup capabilities.',
                'price' => 1999.99,
                'stock_quantity' => 4,
                'category' => 'pcs',
                'likes' => 367,
                'image_url' => 'https://images.unsplash.com/photo-1624705002806-5d72df19c3ad?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'RGB Gaming Showcase',
                'description' => 'Eye-catching RGB build with custom water cooling.',
                'price' => 2599.99,
                'stock_quantity' => 6,
                'category' => 'pcs',
                'likes' => 721,
                'image_url' => 'https://images.unsplash.com/photo-1625328374572-799e8e8b24e8?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Silent Office Workstation',
                'description' => 'Whisper-quiet PC for office work with Intel i5-13400.',
                'price' => 749.99,
                'stock_quantity' => 15,
                'category' => 'pcs',
                'likes' => 189,
                'image_url' => 'https://images.unsplash.com/photo-1623677243147-3b5f7a7e4beb?w=600&h=400&fit=crop',
            ],

            // HEADPHONES
            [
                'name' => 'Sony WH-1000XM5',
                'description' => 'Industry-leading noise cancellation with 30-hour battery life.',
                'price' => 349.99,
                'stock_quantity' => 42,
                'category' => 'headphones',
                'likes' => 1245,
                'image_url' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Bose QuietComfort Ultra',
                'description' => 'Legendary comfort with world-class noise cancellation.',
                'price' => 329.99,
                'stock_quantity' => 28,
                'category' => 'headphones',
                'likes' => 967,
                'image_url' => 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'SteelSeries Arctis Nova Pro',
                'description' => 'Premium gaming headset with Hi-Res audio.',
                'price' => 179.99,
                'stock_quantity' => 33,
                'category' => 'headphones',
                'likes' => 543,
                'image_url' => 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'HyperX Cloud Alpha Wireless',
                'description' => 'Gaming headset with incredible 300-hour battery life.',
                'price' => 149.99,
                'stock_quantity' => 51,
                'category' => 'headphones',
                'likes' => 789,
                'image_url' => 'https://images.unsplash.com/photo-1545127398-14699f92334b?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Audio-Technica ATH-M50xBT2',
                'description' => 'Professional studio monitor headphones with Bluetooth.',
                'price' => 199.99,
                'stock_quantity' => 24,
                'category' => 'headphones',
                'likes' => 432,
                'image_url' => 'https://images.unsplash.com/photo-1577174881658-0f30157c609b?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Razer BlackShark V2 Pro',
                'description' => 'Esports gaming headset with THX Spatial Audio.',
                'price' => 129.99,
                'stock_quantity' => 37,
                'category' => 'headphones',
                'likes' => 621,
                'image_url' => 'https://images.unsplash.com/photo-1599669454699-248893623440?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Sennheiser HD 660S2',
                'description' => 'Audiophile-grade open-back headphones.',
                'price' => 449.99,
                'stock_quantity' => 12,
                'category' => 'headphones',
                'likes' => 278,
                'image_url' => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Logitech G Pro X 2',
                'description' => 'Wireless gaming headset designed with pro gamers.',
                'price' => 249.99,
                'stock_quantity' => 19,
                'category' => 'headphones',
                'likes' => 512,
                'image_url' => 'https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=600&h=400&fit=crop',
            ],

            // TVS
            [
                'name' => 'Samsung 55" QLED 4K',
                'description' => 'Quantum Dot technology with 120Hz refresh rate.',
                'price' => 899.99,
                'stock_quantity' => 14,
                'category' => 'tvs',
                'likes' => 687,
                'image_url' => 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'LG 65" OLED C3',
                'description' => 'Stunning OLED display with perfect blacks.',
                'price' => 1799.99,
                'stock_quantity' => 9,
                'category' => 'tvs',
                'likes' => 1123,
                'image_url' => 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Sony 75" 4K LED Bravia',
                'description' => 'Large 75-inch display with Triluminos Pro.',
                'price' => 1299.99,
                'stock_quantity' => 0,
                'category' => 'tvs',
                'likes' => 534,
                'image_url' => 'https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'TCL 50" QLED 4K',
                'description' => 'Budget-friendly QLED TV with Dolby Vision.',
                'price' => 549.99,
                'stock_quantity' => 27,
                'category' => 'tvs',
                'likes' => 412,
                'image_url' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Samsung 85" Neo QLED 8K',
                'description' => 'Massive 85-inch 8K TV with Mini LED technology.',
                'price' => 3499.99,
                'stock_quantity' => 3,
                'category' => 'tvs',
                'likes' => 892,
                'image_url' => 'https://images.unsplash.com/photo-1601944177325-f8867652837f?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'LG 48" OLED A2',
                'description' => 'Compact OLED TV perfect for gaming with 4K@120Hz.',
                'price' => 799.99,
                'stock_quantity' => 16,
                'category' => 'tvs',
                'likes' => 623,
                'image_url' => 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Hisense 65" ULED 4K',
                'description' => 'Excellent value TV with quantum dot technology.',
                'price' => 699.99,
                'stock_quantity' => 21,
                'category' => 'tvs',
                'likes' => 367,
                'image_url' => 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=600&h=400&fit=crop',
            ],
            [
                'name' => 'Sony A95K 77" QD-OLED',
                'description' => 'Premium QD-OLED technology with unprecedented brightness.',
                'price' => 4999.99,
                'stock_quantity' => 2,
                'category' => 'tvs',
                'likes' => 1567,
                'image_url' => 'https://images.unsplash.com/photo-1571607388263-1044f9ea01dd?w=600&h=400&fit=crop',
            ],
        ];

        foreach ($products as $product) {
            DB::table('products')->insert([
                'name' => $product['name'],
                'description' => $product['description'],
                'price' => $product['price'],
                'stock_quantity' => $product['stock_quantity'],
                'category' => $product['category'],
                'likes' => $product['likes'],
                'image_url' => $product['image_url'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}